services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - nginx-proxy-manager_default


networks:
  nginx-proxy-manager_default:
    external: true