services:
  subdomainly-app:
    container_name: subdomainly-app
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - nginx-proxy-manager_default


networks:
  nginx-proxy-manager_default:
    external: true