services:
  subdomainly-app:
    container_name: subdomainly-app
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    networks:
      - npm_networks

networks:
  npm_networks:
    external: true
