services:
  subdomainly-app:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    networks:
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true